---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 2 with R (STAT 301-2)
author: "Olivia Harbison"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[My Github Repo Link](https://github.com/stat301-2-2024-winter/final-project-2-oliviaharbison.git)

:::

## Data source

This dataset used data from a Spotify API that contains information about 160,000 songs. The information includes identifying variables (ex. song title) and numerical data (ex. danceability). There are 5 character variables, 1 date variable, and 39 numerical variables.^[This dataset can be found [here](https://www.kaggle.com/datasets/elemento/music-albums-popularity-prediction?select=train.csv) on kaggle.]


## Analysis Plan

For my data analysis, I'm going to split the data into training and testing groups. The training group will be 80% of the data, which is 15,594 observations. The testing group will be the remaining 20%, which is 3,902. This split will be stratified by the target variable (`popularity`). Furthermore, I will implement resampling via v-fold cross validation. For this, I will use 5 folds and 3 repeats because the dataset is quite large and my computer may not be able to handle much more. 

Once I've split and folded the data, I will generate recipes and models. I will use two recipes. One will be a "kitchen sink recipe," in which I use all of the possible predictor variables. The other will be more nuanced and based off of my data analysis and exploration. This recipe will include relevant interaction terms, necessary transformations, variable normalization, and more. 


an analysis plan: data splitting, resampling (cross-validation, bootstrap, etc), which model types, how many recipes, etc. Note that students should have this mapped out in their GitHub repo. That is, there should be place holder R scripts created. You don't have to have everything coded, but the overall structure should be evident.   


## Fitted Models

Two model types should be defined and fitted to the resamples: null/baseline model and one other model type (likely standard linear or logistic model):
The recipe can be very basic since we just want to see if you can get things running


## Progress Update

Students should summarize their progress, where they are at, and what their next steps will be. Identifying and potential issues or concerns would be a good idea too.